on:
  pull_request:
    types: [opened, reopened]

jobs: 
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install project dependencies using uv
      run: |
        uv install

    - name: Test with pytest
      run: |
        uv run pytest \
          --doctest-modules \
          --junitxml=junit/test-results.xml \
          --cov=com \
          --cov-report=xml \
          --cov-report=html
